Repository nextcloud/android-common, pull requests merged in 2024-03, with the labels that each got.

#316 Add Jetpack Compose ColorScheme support
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  ui/build.gradle
  ui/src/main/java/com/nextcloud/android/common/ui/theme/ViewThemeUtilsBase.kt
  ui/src/main/java/com/nextcloud/android/common/ui/util/extensions/SchemeExtensions.kt
Labels: 3. to review

#318 Add reuse compliance badge and correct license badge
  README.md
Labels: 3. to review

#321 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
  LICENSES/AGPL-3.0-or-later.txt
Labels: 3. to review, dependencies, automated

#208 Migrate Scheme to DynamicScheme
  ui/src/main/java/com/nextcloud/android/common/ui/theme/MaterialSchemes.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/MaterialSchemesImpl.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/ViewThemeUtilsBase.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidXViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/ColorRole.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/DialogViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/SwitchColorUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/util/extensions/SchemeExtensions.kt
Labels: 3. to review, technical debt

#325 Remove deprecated android.defaults.buildfeatures.buildconfig
  gradle.properties
Labels: 3. to review, technical debt
