Repository nextcloud/android-common, pull requests merged in 2024-11, with the labels that each got.

#547 fix colors for chips to reflect m3 spec
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
Labels: 4. to release, bug

#549 Bump to SDK35
  ui/build.gradle
Labels: 4. to release

#551 sdk35 part 2
  core/build.gradle
  sample/build.gradle
Labels: 3. to review
