Repository nextcloud/android-common, pull requests merged in 2024-02, with the labels that each got.

#291 Add theme utils from MoneyBuster
  README.md
  gradle/verification-metadata.xml
  ui/build.gradle
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidXViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
Labels: enhancement

#298 Remove dependabot due to the adoption of renovate bot
  .github/dependabot.yml
Labels: technical debt

#299 Add SPDX headers, unify licensing
  build.gradle
  core/build.gradle
  core/src/main/AndroidManifest.xml
  core/src/main/java/com/nextcloud/android/common/core/SampleLibraryClass.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  material-color-utilities/build.gradle
  sample/build.gradle
  sample/proguard-rules.pro
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/nextcloud/android/common/sample/MainActivity.kt
  sample/src/main/java/com/nextcloud/android/common/sample/MainViewModel.kt
  sample/src/main/res/drawable/ic_check.xml
  sample/src/main/res/drawable/ic_close.xml
  sample/src/main/res/drawable/ic_directions_car.xml
  sample/src/main/res/drawable/ic_launcher_background.xml
  sample/src/main/res/drawable/ic_launcher_foreground.xml
  sample/src/main/res/layout/activity_main.xml
  sample/src/main/res/mipmap/ic_launcher.xml
  sample/src/main/res/values-night/themes.xml
  sample/src/main/res/values/colors.xml
  sample/src/main/res/values/dimens.xml
  sample/src/main/res/values/strings.xml
  sample/src/main/res/values/themes.xml
  settings.gradle
  ui/build.gradle
  ui/src/main/AndroidManifest.xml
  ui/src/main/java/com/nextcloud/android/common/ui/color/ColorUtil.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/MaterialSchemes.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/MaterialSchemesImpl.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/ServerTheme.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/ViewThemeUtilsBase.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidXViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/ColorRole.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/DialogViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/SwitchColorUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/util/ColorStateListUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/util/PlatformThemeUtil.kt
  ui/src/main/res/values/dimens.xml
Labels: 3. to review

#300 Add further SPDX headers
  .editorconfig
  .gitignore
  README.md
  jitpack.yml
  scripts/analysis/analysis-wrapper.sh
  scripts/hooks/pre-commit
Labels: 3. to review

#307 SPDX headers and reuse config
  .github/workflows/assemble.yml
  .github/workflows/check.yml
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  LICENSES/GPL-3.0-or-later.txt
Labels: technical debt
