Repository nextcloud/android-common, pull requests merged in 2024-04, with the labels that each got.

#363 Revert back to gradle 8.6
  gradle/wrapper/gradle-wrapper.properties
Labels: technical debt

#365 Update material color utils
  material-color-utilities/src/main/java/contrast/Contrast.java
  material-color-utilities/src/main/java/dislike/DislikeAnalyzer.java
  material-color-utilities/src/main/java/dynamiccolor/ContrastCurve.java
  material-color-utilities/src/main/java/dynamiccolor/DynamicColor.java
  material-color-utilities/src/main/java/dynamiccolor/DynamicScheme.java
  material-color-utilities/src/main/java/dynamiccolor/MaterialDynamicColors.java
  material-color-utilities/src/main/java/dynamiccolor/Variant.java
  material-color-utilities/src/main/java/scheme/DynamicScheme.java
  material-color-utilities/src/main/java/scheme/Scheme.java
  material-color-utilities/src/main/java/scheme/SchemeContent.java
  material-color-utilities/src/main/java/scheme/SchemeExpressive.java
  material-color-utilities/src/main/java/scheme/SchemeFidelity.java
  material-color-utilities/src/main/java/scheme/SchemeFruitSalad.java
  material-color-utilities/src/main/java/scheme/SchemeMonochrome.java
  material-color-utilities/src/main/java/scheme/SchemeNeutral.java
  material-color-utilities/src/main/java/scheme/SchemeRainbow.java
  material-color-utilities/src/main/java/scheme/SchemeTonalSpot.java
  material-color-utilities/src/main/java/scheme/SchemeVibrant.java
  material-color-utilities/src/main/java/temperature/TemperatureCache.java
  ui/src/main/java/com/nextcloud/android/common/ui/theme/MaterialSchemes.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/MaterialSchemesImpl.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/ViewThemeUtilsBase.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/ColorRole.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/SwitchColorUtils.kt
  ui/src/main/java/com/nextcloud/android/common/ui/util/extensions/SchemeExtensions.kt
Labels: 4. to release, technical debt

#378 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies
